package edu.upv.poo.ui;

import edu.upv.poo.App;
import edu.upv.poo.dataaccess.Editorial;
import edu.upv.poo.dataaccess.EditorialDao;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisroberto
 */
public class EditorialesFrame extends javax.swing.JFrame {

    private Editorial[] editoriales;
    
    /**
     * Creates new form EditorialesFrame
     */
    public EditorialesFrame() {
        initComponents();
        consultarEditoriales();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditoriales = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblEditoriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Pais", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEditoriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditorialesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEditoriales);

        btnAgregar.setBackground(new java.awt.Color(25, 118, 210));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        EditorialesAgregarFrame form = new EditorialesAgregarFrame(null);
        form.setEditorialGuardadoListener(this::editorialGuardado);
        form.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblEditorialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditorialesMouseClicked
        // TODO add your handling code here:
        
        int ix = tblEditoriales.getSelectedRow();
        if (ix == -1 || evt.getClickCount() != 2) return;
        Editorial editorial = editoriales[ix];
        
        EditorialesAgregarFrame form = new EditorialesAgregarFrame(editorial);
        form.setEditorialGuardadoListener(this::editorialGuardado);
        form.setVisible(true);
        
        System.out.println(editorial.getNombre());
        
    }//GEN-LAST:event_tblEditorialesMouseClicked

    private void consultarEditoriales() {
        editoriales = null;
        try (Connection connection = App.getConnection()) {
            EditorialDao editorialDbDao = App.getEditorialDao(connection);
            editoriales = editorialDbDao.getAll();
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los datos: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
        }
        cargarTblEditoriales();
    }
    
    private void editorialGuardado(String accion, Editorial editorialGuardado) {
        consultarEditoriales();
        cargarTblEditoriales();
    }
    
    private void cargarTblEditoriales() {
        DefaultTableModel tblModel = (
                DefaultTableModel)tblEditoriales.getModel();
        
        while (tblModel.getRowCount() != 0) tblModel.removeRow(0);
        if (editoriales == null) return;
        
        for (int i = 0; i < editoriales.length; i++) {
            tblModel.insertRow(i, toRow(editoriales[i]));
        }
        
    }
    
    private Object[] toRow(Editorial i) {
        return new Object[] {
            i.getNombre(), i.getPais(), i.getEmail()
        };
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEditoriales;
    // End of variables declaration//GEN-END:variables
}
