
package edu.upv.poo.ui;

import java.sql.*;

import edu.upv.poo.App;
import edu.upv.poo.dataaccess.LibroInventarioV;
import javax.swing.JOptionPane;


/**
 *
 * @author oscar
 */
public class LibroInventarioForm extends javax.swing.JFrame {
    
    private LibroInventarioForm.LibroInventarioListener  libroInventarioListener;
    private LibroInventarioV libroInventarioV;
    /**
     * Creates new form LibroInventarioForm
     */
    public LibroInventarioForm(LibroInventarioV libroInventarioV) {
        initComponents();
        this.libroInventarioV = libroInventarioV;
        llenarCamposEdicion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAplicarEdicion = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Estado:");

        btnAplicarEdicion.setBackground(new java.awt.Color(25, 118, 210));
        btnAplicarEdicion.setForeground(new java.awt.Color(255, 255, 255));
        btnAplicarEdicion.setText("Aplicar edición");
        btnAplicarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarEdicionActionPerformed(evt);
            }
        });

        jLabel4.setText("Edición del inventario");

        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAplicarEdicion, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txtEstado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAplicarEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAplicarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarEdicionActionPerformed
        
        String sql = "UPDATE libros_inventario SET estado = ? WHERE id = ?";
        try(Connection connection = App.getConnection()){
            try(CallableStatement stmt = connection.prepareCall(sql)){
                stmt.setString(1, txtEstado.getText());
                System.out.println(libroInventarioV.getInventarioId());
                stmt.setInt(2, libroInventarioV.getInventarioId());
                stmt.execute();
                getLibroInventarioListener().editarInventario();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
        }
        JOptionPane.showMessageDialog(null, "Guardado con exito. " ,"Exito!", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_btnAplicarEdicionActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed
    
    public void setLibroInventarioListener(LibroInventarioForm.LibroInventarioListener l) {
        this.libroInventarioListener = l;
    }
    
    public LibroInventarioForm.LibroInventarioListener getLibroInventarioListener() {
        return libroInventarioListener;
    }

    private void llenarCamposEdicion() {
        txtEstado.setText(libroInventarioV.getEstado());
    }
    
    public interface LibroInventarioListener{
        void editarInventario();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAplicarEdicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEstado;
    // End of variables declaration//GEN-END:variables
}
