/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.upv.poo.ui;

import edu.upv.poo.App;
import edu.upv.poo.dataaccess.Editorial;
import edu.upv.poo.dataaccess.EditorialDbDao;
import edu.upv.poo.dataaccess.Libro;
import edu.upv.poo.dataaccess.LibroInventario;
import edu.upv.poo.dataaccess.LibroInventarioDbDao;
import edu.upv.poo.dataaccess.LibroInventarioExistenciaV;
import edu.upv.poo.dataaccess.LibroInventarioExistenciaVDbDao;
import edu.upv.poo.dataaccess.TipoRecurso;
import edu.upv.poo.dataaccess.TipoRecursoDbDao;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class LibrosInventarioExistenciaFrame extends javax.swing.JFrame {

    private LibroInventarioExistenciaV[] libros;

    /**
     * Creates new form LibrosFrame
     */

    public LibrosInventarioExistenciaFrame() {
        initComponents();
        this.consultarLibros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        btn_agregar = new javax.swing.JButton();
        btn_agregarEnInventario = new javax.swing.JButton();
        btnBorrarLibro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Id del tipo de recurso", "Tipo de recurso", "Tipo de Recurso Activo", "Edición", "Id Editorial", "Editorial", "País del editorial", "Email del editorial", "Editorial activo", "Autores", "ISBN", "Activo", "Cantidad en inventario"
            }
        ));
        tbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl.setFocusable(false);
        tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl.getTableHeader().setReorderingAllowed(false);
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);
        tbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btn_agregar.setBackground(new java.awt.Color(25, 118, 210));
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_agregarEnInventario.setBackground(new java.awt.Color(25, 118, 210));
        btn_agregarEnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregarEnInventario.setText("Agregar en inventario");
        btn_agregarEnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarEnInventarioActionPerformed(evt);
            }
        });

        btnBorrarLibro.setBackground(new java.awt.Color(25, 118, 210));
        btnBorrarLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarLibro.setText("Borrar Libro");
        btnBorrarLibro.setToolTipText("");
        btnBorrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_agregarEnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agregarEnInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBorrarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        LibrosAgregarFrame form = new LibrosAgregarFrame(null);
        form.setLibroGuardadoListener(this::libroGuardado);
        form.setVisible(true);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int index = tbl.getSelectedRow();
        Libro[] libros = null;
        try(Connection connection = App.getConnection()){
            libros = App.getLibrosDao(connection).getAll();
        } catch (SQLException ex) {
            
        } catch (Exception ex) {
            
        }
        if(evt.getClickCount()==2){
            LibrosAgregarFrame form = new LibrosAgregarFrame(libros[index]);
            form.setLibroGuardadoListener(this::libroGuardado);
            form.setVisible(true);
        }
    }//GEN-LAST:event_tblMouseClicked

    private void btn_agregarEnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarEnInventarioActionPerformed
        // TODO add your handling code here:
        if(tbl.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Seleccione un campo ","Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try(Connection connection = App.getConnection()){
            LibroInventario l = new LibroInventario();
            LibroInventarioDbDao lidbdao = App.getLibrosInventarioDao(connection);
            l.setLibroId(libros[tbl.getSelectedRow()].getId());
            String estado = JOptionPane.showInputDialog("Ingrese el estado");
            if(estado == null)return;
            if(estado.isEmpty())return;
            if(estado.isBlank())return;
            l.setEstado(estado);
            l.setDisponible(true);
            lidbdao.insert(l);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los datos: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error al obtener los datos: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
        }
        JOptionPane.showMessageDialog(null, "Guardado en inventario con exito. " + libros[tbl.getSelectedRowCount()-1].getId() ,"Exito!", JOptionPane.INFORMATION_MESSAGE);
        consultarLibros();
    }//GEN-LAST:event_btn_agregarEnInventarioActionPerformed

    private void btnBorrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarLibroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarLibro;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_agregarEnInventario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
    
    private void consultarLibros() {
        libros = null;
        try (Connection connection = App.getConnection()) {
            LibroInventarioExistenciaVDbDao librosDbDao = App.getLibrosInventarioExistenciaVDao(connection);
            libros = librosDbDao.getAll();
            cargarTblEditoriales();
        } 
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al obtener los datos: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void libroGuardado(String accion, Libro libroGuardado) {
        consultarLibros();
    }
    
    private void cargarTblEditoriales() throws Exception {
        DefaultTableModel tblModel = (
                DefaultTableModel)tbl.getModel();
        while (tblModel.getRowCount() != 0) tblModel.removeRow(0);
        if (libros == null) return;
        for (int i = 0; i < libros.length; i++) {
            tblModel.insertRow(i, toRow(libros[i]));
        }
        
    }

    private Object[] toRow(LibroInventarioExistenciaV i) throws Exception {
        
        return new Object[] {
            i.getTitulo(), i.getTipoRecursoId(),i.getTipoRecursoNombre(),
            i.isTipoRecursoActivo(), i.getEdicion(),i.getEditorialId(),
            i.getEditorialNombre(),i.getEditorialPais(),i.getEditorialEmail(),
            i.isEditorialActivo(),i.getAutores(),i.getIsbn(),i.isActivo(),
            i.getCantidadEnInventario()
        };
    }
}
