/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upv.poo.ui;


import edu.upv.poo.App;
import edu.upv.poo.dataaccess.LibroInventario;
import edu.upv.poo.dataaccess.LibroInventarioDbDao;
import edu.upv.poo.dataaccess.Prestamo;
import edu.upv.poo.dataaccess.PrestamoDbDao;
import edu.upv.poo.dataaccess.PrestamoV;
import edu.upv.poo.dataaccess.PrestamoVDbDao;
import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */
public class PrestamoDevolucionFrame extends javax.swing.JFrame {
    
    PrestamoV[] prestamos = null;
    
    /**
     * Creates new form LibroInventarioList
     * 
     */
    
    public PrestamoDevolucionFrame() {
        initComponents();
        try(Connection connection = App.getConnection()){
            prestamos = App.getPrestamosVDao(connection).getAll();
            llenarTabla();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
           ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_devolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_devolver.setBackground(new java.awt.Color(25, 118, 210));
        btn_devolver.setForeground(new java.awt.Color(255, 255, 255));
        btn_devolver.setText("Devolver");
        btn_devolver.setActionCommand("");
        btn_devolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_devolverMouseClicked(evt);
            }
        });
        btn_devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolverActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "id del libro en inventario", "libro id", "titulo del libro", "tipo de recurso del libro", "edicion del libro", "editorial del libro", "autores del libro", "isbn del libro", "estado del libro", "id del alumno", "nombre del alumno", "apellidos del alumno", "carrera del alumno", "fecha de prestamo", "fecha de devolución", "fecha devuelto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);
        if (tbl.getColumnModel().getColumnCount() > 0) {
            tbl.getColumnModel().getColumn(15).setResizable(false);
            tbl.getColumnModel().getColumn(16).setResizable(false);
        }

        jLabel1.setText("Matricula:");

        btnBuscar.setBackground(new java.awt.Color(25, 118, 210));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTitulo)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1295, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String matricula = txtTitulo.getText();
        if (matricula != null){
            try (Connection connection = App.getConnection()){
                PrestamoVDbDao pvdbdao = new PrestamoVDbDao(connection);
                try{
                    prestamos = pvdbdao.getByAlumno(Integer.parseInt(matricula));
                    llenarTabla();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
                }
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btn_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolverActionPerformed
        if(tbl.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Error! seleccione uan fila","Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try(Connection connection = App.getConnection()){
            if (prestamos == null) return;
            ArrayList<PrestamoV> ps = new ArrayList<PrestamoV>();
            for(int i = 0;i<prestamos.length;i++){
                if(prestamos[i].getFechaDevuelto()==null)ps.add(prestamos[i]);
            }
            PrestamoDbDao pdbdao = App.getPrestamosDao(connection);
            Prestamo p = pdbdao.getById(ps.get(tbl.getSelectedRow()).getId());
            p.setFechaDevuelto(LocalDateTime.now());
            pdbdao.update(p);
            LibroInventarioDbDao ldbdao = App.getLibrosInventarioDao(connection);
            LibroInventario l = ldbdao.getById(p.getLibroInventarioId());
            l.setEstado("Activo");
            ldbdao.update(l);
            llenarTabla();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
            //System.out.println(ex);
            return;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
            //System.out.println(ex);
            return;
        }
        JOptionPane.showMessageDialog(null, "Devuelto con exito. " ,"Exito!", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btn_devolverActionPerformed

    private void btn_devolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_devolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_devolverMouseClicked
     /**
     * 
     * Overloading del método buscar
     * 
     */
    private void btnBuscarActionPerformed() {
        String matricula = txtTitulo.getText();
        if (matricula != null){
            try (Connection connection = App.getConnection()){
                PrestamoVDbDao pvdbdao = new PrestamoVDbDao(connection);
                try{
                    prestamos = pvdbdao.getByAlumno(Integer.parseInt(matricula));
                    llenarTabla();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
                }
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
    } 
            
    
    private void llenarTabla(){
        if (prestamos == null) return;
        ArrayList<PrestamoV> p = new ArrayList<PrestamoV>();
        for(int i = 0;i<prestamos.length;i++){
            if(prestamos[i].getFechaDevuelto()==null)p.add(prestamos[i]);
        }
        DefaultTableModel model = (DefaultTableModel)tbl.getModel();
        while (model.getRowCount() > 0) model.removeRow(0);
        for (int i = 0; i < p.size(); i++) {
            model.insertRow(i, getRowOf(p.get(i)));
        }
    }
    
    private void eliminarDevueltos(){

    }
    
    private Object[] getRowOf(PrestamoV p) {
        System.out.println(p.getLibroEstado());
        return new Object[] {
            p.getId(),
            p.getLibroInventarioId(),
            p.getLibroId(),
            p.getLibroTitulo(),
            p.getLibroTipoRecursoNombre(),
            p.getLibroEdicion(),
            p.getLibroEditorialNombre(),
            p.getLibroAutores(),
            p.getLibroIsbn(),
            p.getLibroEstado(),
            p.getAlumnoId(),
            p.getAlumnoNombre(),
            p.getAlumnoApellidos(),
            p.getAlumnoCarreraNombre(),
            p.getFechaPrestamo(),
            p.getFechaDebeDevolver(),
            p.getFechaDevuelto()
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btn_devolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

}
